In [129]:
from __future__ import division
import matplotlib.pyplot as plt
import pandas as pds
import seaborn as sns
import numpy as np
import random
from sklearn import tree
from sklearn import ensemble
from sklearn import metrics
from scipy import stats
#import graphviz
from sklearn.model_selection import train_test_split
%matplotlib inline
from sklearn.preprocessing import StandardScaler

In [130]:
#df = sns.load_dataset('iris') # load a pandas dataframe from demo file
df = pds.read_csv('./weather.csv', sep=",") # load a pandas dataframe from csv
df.head()


Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure     Rain
0    23.720338  89.592641    7.335604    50.501694  1032.378759     rain
1    27.879734  46.489704    5.952484     4.990053   992.614190  no rain
2    25.069084  83.072843    1.371992    14.855784  1007.231620  no rain
3    23.622080  74.367758    7.050551    67.255282   982.632013     rain
4    20.591370  96.858822    4.643921    47.676444   980.825142  no rain

In [131]:
dff = df.drop(['Rain'],axis=1) # get only the features in the dataframe
dff = df.drop(['Rain','Wind_Speed','Cloud_Cover'],axis=1)

In [132]:
dff.head()

Temperature   Humidity     Pressure
0    23.720338  89.592641  1032.378759
1    27.879734  46.489704   992.614190
2    25.069084  83.072843  1007.231620
3    23.622080  74.367758   982.632013
4    20.591370  96.858822   980.825142

In [133]:
# Compter le nombre de lignes où 'Rain' est égal à 'no rain'
no_rain_count = len(df[df['Rain'] == 'no rain'])
rain_count = len(df[df['Rain'] == 'rain'])
# Affichage du nombre de lignes 'no rain'
print(no_rain_count, rain_count)

2186 314


In [135]:
# Supposons que votre DataFrame s'appelle df

# Sélectionner aléatoirement 1700 lignes où 'Rain' est égal à 'no rain'
df_no_rain = df[df['Rain'] == 'no rain'].sample(n=1800, random_state=42)

# Supprimer ces 1700 lignes de 'no rain' du DataFrame original
df_balanced = df.drop(df_no_rain.index)

# Vérification du nouveau nombre de lignes
no_rain_count_balanced = len(df_balanced[df_balanced['Rain'] == 'no rain'])
rain_count_balanced = len(df_balanced[df_balanced['Rain'] == 'rain'])

print(no_rain_count_balanced, rain_count_balanced)

df=df_balanced

386 314


In [142]:
classes = df.loc[:,"Rain"]
# Réduire la taille de 'classes' pour qu'elle corresponde à 'dff'
classes = classes.sample(n=df.shape[0], random_state=10)

In [143]:
classes=df['Rain'].map({'rain':1, 'no rain':0})

In [144]:
print(dff.shape)  # Affiche les dimensions de dff
print(classes.shape)  # Affiche les dimensions de classes

(700, 6)
(700,)


In [168]:
dff = df.drop(['Rain'],axis=1) # get only the features in the dataframe
dff = df.drop(['Rain','Wind_Speed','Cloud_Cover'],axis=1)
dff.head()

Temperature   Humidity     Pressure
0     23.720338  89.592641  1032.378759
2     25.069084  83.072843  1007.231620
3     23.622080  74.367758   982.632013
9     19.586038  82.978293  1036.503457
11    23.222373  76.877943   980.108934

In [169]:
#X_train, X_test, y_train, y_test = train_test_split(dff, classes, train_size=0.66)
X_train, X_test, y_train, y_test = train_test_split(dff, classes, test_size=0.33, random_state=10)

In [170]:
type(X_train)
# Vérifier les types des colonnes
print(X_train.dtypes)

Temperature    float64
Humidity       float64
Pressure       float64
dtype: object


In [171]:
model = ensemble.RandomForestClassifier(n_estimators=50, criterion = 'entropy', random_state=10,
                                        min_samples_leaf=3,bootstrap=True)

In [172]:
model.fit(X_train, y_train)
sortedLabelList = sorted(list(set(classes)))
print(sortedLabelList)
y_predict_train = model.predict(X_train)
metrics.confusion_matrix(y_true=y_train, y_pred=y_predict_train, labels=sortedLabelList)


[0, 1]


array([[230,  26],
       [  0, 213]])

In [173]:
y_predict = model.predict(X_test)
print(y_predict[0:5])
print(metrics.accuracy_score(y_test, y_predict))

[0 0 0 0 0]
0.9047619047619048


In [174]:
sortedLabelList = sorted(list(set(classes)))
metrics.confusion_matrix(y_true=y_test, y_pred=y_predict, labels=sortedLabelList)

array([[110,  20],
       [  2,  99]])

In [175]:
sortedLabelList

[0, 1]

In [176]:
pds.DataFrame(
    metrics.confusion_matrix(y_true=y_test, y_pred=y_predict, labels=sortedLabelList),
    columns=['Predicted ' + className for className in sortedLabelList],
    index=['True ' + className for className in sortedLabelList]
)

TypeError: can only concatenate str (not "int") to str

In [177]:
print(metrics.classification_report(y_test, y_predict))  

              precision    recall  f1-score   support

           0       0.98      0.85      0.91       130
           1       0.83      0.98      0.90       101

    accuracy                           0.90       231
   macro avg       0.91      0.91      0.90       231
weighted avg       0.92      0.90      0.91       231



In [178]:
pds.DataFrame(model.predict_proba(X_test),
    columns=['Predicted ' + className for className in sortedLabelList]).head(10)

TypeError: can only concatenate str (not "int") to str